// This code was generated by a vsSolutionBuildEvent. 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
using System;

namespace net.r_eg.hashing
{
    public static class HuidVersion
    {
        public const string PRODUCT = "1.0.0";

        public const string NUMBER = "1.0.0";

        public const string B_SHA1 = "-";

        public static readonly Version number = new(NUMBER);
    }
}